/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dorsetscreen;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author lukfd
 */
public class AccessScreen extends javax.swing.JFrame {

    /**
     * Creates new form AccessScreen
     */
    public AccessScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MenuRegister = new javax.swing.JMenu();
        MenuUsers = new javax.swing.JMenuItem();
        MenuFinance = new javax.swing.JMenu();
        MenuPayment = new javax.swing.JMenuItem();
        MenuCourses = new javax.swing.JMenu();
        MenuLecturerAttendance = new javax.swing.JMenuItem();
        MenuStudentAttendance = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MenuAssignmentConsult = new javax.swing.JMenuItem();
        MenuAssignmentInput = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuExamConsult = new javax.swing.JMenuItem();
        MenuExamInput = new javax.swing.JMenuItem();
        MenuModule = new javax.swing.JMenuItem();
        MenuGrade = new javax.swing.JMenuItem();
        MenuCalendar = new javax.swing.JMenu();
        MenuActivities = new javax.swing.JMenuItem();
        MenuTimetable = new javax.swing.JMenuItem();
        MenuHelp = new javax.swing.JMenu();
        MenuAbout = new javax.swing.JMenuItem();
        MenuOptions = new javax.swing.JMenu();
        MenuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Virtual Global College");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ABC.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("User");
        lblUsuario.setToolTipText("");
        lblUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblData.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData.setText("Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(lblUsuario)
                .addGap(58, 58, 58)
                .addComponent(lblData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuRegister.setText("Register");

        MenuUsers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        MenuUsers.setText("Users");
        MenuUsers.setEnabled(false);
        MenuUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUsersActionPerformed(evt);
            }
        });
        MenuRegister.add(MenuUsers);

        Menu.add(MenuRegister);

        MenuFinance.setText("Finance");

        MenuPayment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        MenuPayment.setText("Payment");
        MenuPayment.setEnabled(false);
        MenuPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPaymentActionPerformed(evt);
            }
        });
        MenuFinance.add(MenuPayment);

        Menu.add(MenuFinance);

        MenuCourses.setText("Course");

        MenuLecturerAttendance.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        MenuLecturerAttendance.setText("Lecturer Attendance");
        MenuLecturerAttendance.setEnabled(false);
        MenuLecturerAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLecturerAttendanceActionPerformed(evt);
            }
        });
        MenuCourses.add(MenuLecturerAttendance);

        MenuStudentAttendance.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        MenuStudentAttendance.setText("Student Attendance");
        MenuStudentAttendance.setEnabled(false);
        MenuStudentAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuStudentAttendanceActionPerformed(evt);
            }
        });
        MenuCourses.add(MenuStudentAttendance);

        jMenu1.setText("Assignment");

        MenuAssignmentConsult.setText("Student");
        MenuAssignmentConsult.setEnabled(false);
        MenuAssignmentConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAssignmentConsultActionPerformed(evt);
            }
        });
        jMenu1.add(MenuAssignmentConsult);

        MenuAssignmentInput.setText("Lecturer");
        MenuAssignmentInput.setEnabled(false);
        MenuAssignmentInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAssignmentInputActionPerformed(evt);
            }
        });
        jMenu1.add(MenuAssignmentInput);

        MenuCourses.add(jMenu1);

        jMenu2.setText("Exam");

        MenuExamConsult.setText("Student");
        MenuExamConsult.setEnabled(false);
        MenuExamConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExamConsultActionPerformed(evt);
            }
        });
        jMenu2.add(MenuExamConsult);

        MenuExamInput.setText("Lecturer");
        MenuExamInput.setEnabled(false);
        MenuExamInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExamInputActionPerformed(evt);
            }
        });
        jMenu2.add(MenuExamInput);

        MenuCourses.add(jMenu2);

        MenuModule.setText("Module Plan");
        MenuModule.setEnabled(false);
        MenuModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuModuleActionPerformed(evt);
            }
        });
        MenuCourses.add(MenuModule);

        MenuGrade.setText("Grade");
        MenuGrade.setEnabled(false);
        MenuGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGradeActionPerformed(evt);
            }
        });
        MenuCourses.add(MenuGrade);

        Menu.add(MenuCourses);

        MenuCalendar.setText("Calendar");

        MenuActivities.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        MenuActivities.setText("Activities");
        MenuActivities.setEnabled(false);
        MenuActivities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActivitiesActionPerformed(evt);
            }
        });
        MenuCalendar.add(MenuActivities);

        MenuTimetable.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        MenuTimetable.setText("Timetable");
        MenuTimetable.setEnabled(false);
        MenuTimetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTimetableActionPerformed(evt);
            }
        });
        MenuCalendar.add(MenuTimetable);

        Menu.add(MenuCalendar);

        MenuHelp.setText("Help");

        MenuAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        MenuAbout.setText("About");
        MenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAboutActionPerformed(evt);
            }
        });
        MenuHelp.add(MenuAbout);

        Menu.add(MenuHelp);

        MenuOptions.setText("Options");

        MenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        MenuExit.setText("Exit");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        MenuOptions.add(MenuExit);

        Menu.add(MenuOptions);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desktop))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(842, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPaymentActionPerformed
        // TODO add your handling code here:
        UserPayment user = new UserPayment();
        user.setVisible(true);
        desktop.add(user);
    }//GEN-LAST:event_MenuPaymentActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null, "Would you like to proceed?", "Attention", JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAboutActionPerformed
        // TODO add your handling code here:
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_MenuAboutActionPerformed

    private void MenuLecturerAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLecturerAttendanceActionPerformed
        // TODO add your handling code here:
        AttendanceScreen attendance = new AttendanceScreen();
        attendance.setVisible(true);
        desktop.add(attendance);
    }//GEN-LAST:event_MenuLecturerAttendanceActionPerformed

    private void MenuUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUsersActionPerformed
        // TODO add your handling code here:
        UserScreen user = new UserScreen();
        user.setVisible(true);
        desktop.add(user);
    }//GEN-LAST:event_MenuUsersActionPerformed

    private void MenuStudentAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuStudentAttendanceActionPerformed
        // TODO add your handling code here:
        StudentAttendanceScreen attendance = new StudentAttendanceScreen();
        attendance.setVisible(true);
        desktop.add(attendance);
    }//GEN-LAST:event_MenuStudentAttendanceActionPerformed

    private void MenuActivitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActivitiesActionPerformed
        // TODO add your handling code here:
        ActivitiesScreen activities = new ActivitiesScreen();
        activities.setVisible(true);
        desktop.add(activities);
    }//GEN-LAST:event_MenuActivitiesActionPerformed

    private void MenuTimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTimetableActionPerformed
        // TODO add your handling code here:
        TimetableScreen timetable = new TimetableScreen();
        timetable.setVisible(true);
        desktop.add(timetable);
    }//GEN-LAST:event_MenuTimetableActionPerformed

    private void MenuAssignmentConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAssignmentConsultActionPerformed
        // TODO add your handling code here:
        StudentAssignmentScreen assignment = new StudentAssignmentScreen();
        assignment.setVisible(true);
        desktop.add(assignment);
    }//GEN-LAST:event_MenuAssignmentConsultActionPerformed

    private void MenuAssignmentInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAssignmentInputActionPerformed
        // TODO add your handling code here:
        AssignmentScreen assignment = new AssignmentScreen();
        assignment.setVisible(true);
        desktop.add(assignment);
    }//GEN-LAST:event_MenuAssignmentInputActionPerformed

    private void MenuExamConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExamConsultActionPerformed
        // TODO add your handling code here:
        StudentExamScreen exam = new StudentExamScreen();
        exam.setVisible(true);
        desktop.add(exam);
    }//GEN-LAST:event_MenuExamConsultActionPerformed

    private void MenuExamInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExamInputActionPerformed
        // TODO add your handling code here:
        ExamScreen exam = new ExamScreen();
        exam.setVisible(true);
        desktop.add(exam);
    }//GEN-LAST:event_MenuExamInputActionPerformed

    private void MenuModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuModuleActionPerformed
        // TODO add your handling code here:
        ModuleScreen module = new ModuleScreen();
        module.setVisible(true);
        desktop.add(module);
    }//GEN-LAST:event_MenuModuleActionPerformed

    private void MenuGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGradeActionPerformed
        // TODO add your handling code here:
        GradeScreen grade = new GradeScreen();
        grade.setVisible(true);
        desktop.add(grade);
    }//GEN-LAST:event_MenuGradeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccessScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccessScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccessScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccessScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccessScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem MenuAbout;
    public static javax.swing.JMenuItem MenuActivities;
    public static javax.swing.JMenuItem MenuAssignmentConsult;
    public static javax.swing.JMenuItem MenuAssignmentInput;
    private javax.swing.JMenu MenuCalendar;
    private javax.swing.JMenu MenuCourses;
    public static javax.swing.JMenuItem MenuExamConsult;
    public static javax.swing.JMenuItem MenuExamInput;
    private javax.swing.JMenuItem MenuExit;
    public static javax.swing.JMenu MenuFinance;
    public static javax.swing.JMenuItem MenuGrade;
    private javax.swing.JMenu MenuHelp;
    public static javax.swing.JMenuItem MenuLecturerAttendance;
    public static javax.swing.JMenuItem MenuModule;
    private javax.swing.JMenu MenuOptions;
    public static javax.swing.JMenuItem MenuPayment;
    private javax.swing.JMenu MenuRegister;
    public static javax.swing.JMenuItem MenuStudentAttendance;
    public static javax.swing.JMenuItem MenuTimetable;
    public static javax.swing.JMenuItem MenuUsers;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
