/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dorsetscreen;
import java.sql.*;
import dorsetdata.ConnectionModule;
import javax.swing.JOptionPane;
/**
 *
 * @author lukfd
 */
public class GradeScreen extends javax.swing.JInternalFrame {
    Connection conector = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form GradeScreen
     */
    public GradeScreen() {
        initComponents();
        conector = ConnectionModule.conector();
    }
private void consultar() {
        String sql = "select * from tbusuarios where iduser=?";
        try {
            pst = conector.prepareStatement(sql);
            pst.setString(1, txtiduser.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                txtusuario.setText(rs.getString(2));
                cboCourse.setSelectedItem(rs.getString(8));
                txtmodule.setText(rs.getString(13));
                cboSubjects.setSelectedItem(rs.getString(15));
                txtassignmentweight.setText(rs.getString(19));
                txtexamweight.setText(rs.getString(22));
                txtfinalweight.setText(rs.getString(23));
                txtassignmentgrade.setText(rs.getString(24));
                txtexamgrade.setText(rs.getString(25));
                txtfinalgrade.setText(rs.getString(26));
            } else {
                JOptionPane.showMessageDialog(null, "User not found");
                txtiduser.setText(null);
                txtmodule.setText(null);
                cboCourse.setSelectedItem(null);
                cboSubjects.setSelectedItem(null);
                txtexamweight.setText(null);
                txtassignmentweight.setText(null);
                txtfinalweight.setText(null);
                txtassignmentgrade.setText(null);
                txtexamgrade.setText(null);
                txtfinalgrade.setText(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void adicionar() {
        String sql = "update tbusuarios set module=?, assignmentweight=?, finalweight=?, examweight=?, assignmentgrade=?, examgrade=?, finalgrade=? where iduser=?";
        try {
            pst = conector.prepareStatement(sql);
            pst.setString(1, txtmodule.getText());
            pst.setString(2, txtassignmentweight.getText());
            pst.setString(3, txtexamweight.getText());
            pst.setString(4, txtfinalweight.getText());
            pst.setString(5, txtassignmentgrade.getText());
            pst.setString(6, txtexamgrade.getText());
            pst.setString(7, txtfinalgrade.getText());
            pst.setString(8, txtiduser.getText());

            //validating selected fields
            if ((txtusuario.getText().isEmpty())||(txtiduser.getText().isEmpty())|| (txtmodule.getText().isEmpty()) || (txtfinalweight.getText().isEmpty()) || (txtassignmentweight.getText().isEmpty()) || (txtexamweight.getText().isEmpty()) || (txtassignmentgrade.getText().isEmpty()) || (txtexamgrade.getText().isEmpty())){
                JOptionPane.showMessageDialog(null, "Fill in all fields");
            } else {

                // coment: add new user
                int added = pst.executeUpdate();
                System.out.println(added);
                if (added > 0) {
                    JOptionPane.showMessageDialog(null, "Updated successfully");
                    txtiduser.setText(null);
                    txtmodule.setText(null);
                    txtassignmentweight.setText(null);
                    txtexamweight.setText(null);
                    txtfinalweight.setText(null);
                    txtassignmentgrade.setText(null);
                    txtexamgrade.setText(null);
                    txtfinalgrade.setText(null);                    
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdUser3 = new javax.swing.JLabel();
        cboSubjects = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblIdUser = new javax.swing.JLabel();
        lblcourse1 = new javax.swing.JLabel();
        lblcourse = new javax.swing.JLabel();
        txtmodule = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblIdUser5 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        lblIdUser1 = new javax.swing.JLabel();
        cboCourse = new javax.swing.JComboBox<>();
        txtassignmentgrade = new javax.swing.JTextField();
        txtiduser = new javax.swing.JTextField();
        lblIdUser8 = new javax.swing.JLabel();
        txtexamgrade = new javax.swing.JTextField();
        lblIdUser9 = new javax.swing.JLabel();
        txtfinalgrade = new javax.swing.JTextField();
        lblIdUser6 = new javax.swing.JLabel();
        txtfinalweight = new javax.swing.JTextField();
        txtassignmentweight = new javax.swing.JTextField();
        txtexamweight = new javax.swing.JTextField();
        lblIdUser7 = new javax.swing.JLabel();
        lblIdUser12 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Grade Consult");

        lblIdUser3.setText("*Module");

        cboSubjects.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Y1_OOP - Basic Programing", "Y1_Database Management", "Y1_Front-End Development", "Y1_Data Sience", "Y1_Networking & Routing", "Y2_System & Operations", "Y2_DevOps", "Y2_Mobile Development", "Y2_Database Management", "Y2_OOP-Advanced Programing" }));
        cboSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSubjectsActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("GRADES CONSULT");

        jLabel1.setText("*Required Fields");

        lblIdUser.setText("*ID");

        lblcourse1.setText("*Subject");

        lblcourse.setText("*Course");

        txtmodule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmoduleActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconmonstr-magnifier-10-64.png"))); // NOI18N
        btnSearch.setToolTipText("Consult Payment");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.setPreferredSize(new java.awt.Dimension(80, 80));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblIdUser5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIdUser5.setForeground(new java.awt.Color(51, 51, 255));
        lblIdUser5.setText("Assignment");

        lblIdUser1.setText("*Name");

        cboCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "D_BSc_Science in Computing_1_Year", "D_BSc_Science in Computing_2_Year", "D_BSc_Science in Computing_3_Year", "C_BSc_Science in Computing_1_Year", "C_BSc_Science in Computing_2_Year", "C_BSc_Science in Computing_3_Year", "L_BSc_Science in Computing_1_Year", "L_BSc_Science in Computing_2_Year", "L_BSc_Science in Computing_3_Year", "D_BSc_Business_1_Year", "D_BSc_Business_2_Year", "D_BSc_Business_3_Year", "C_BSc_Business_1_Year", "C_BSc_Business_2_Year", "C_BSc_Business_3_Year", "L_BSc_Business_1_Year", "L_BSc_Business_2_Year", "L_BSc_Business_3_Year", "D_BSc_Finance_1_Year", "D_BSc_Finance_2_Year", "D_BSc_Finance_3_Year", "C_BSc_Finance_1_Year", "C_BSc_Finance_2_Year", "C_BSc_Finance_3_Year", "L_BSc_Finance_1_Year", "L_BSc_Finance_2_Year", "L_BSc_Finance_3_Year" }));
        cboCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCourseActionPerformed(evt);
            }
        });

        txtassignmentgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtassignmentgradeActionPerformed(evt);
            }
        });

        txtiduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtiduserActionPerformed(evt);
            }
        });

        lblIdUser8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIdUser8.setForeground(new java.awt.Color(51, 51, 255));
        lblIdUser8.setText("Exam");

        txtexamgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexamgradeActionPerformed(evt);
            }
        });

        lblIdUser9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIdUser9.setForeground(new java.awt.Color(0, 204, 51));
        lblIdUser9.setText("Final Grade");

        txtfinalgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfinalgradeActionPerformed(evt);
            }
        });

        lblIdUser6.setText("Weight");

        txtfinalweight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfinalweightActionPerformed(evt);
            }
        });

        txtassignmentweight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtassignmentweightActionPerformed(evt);
            }
        });

        txtexamweight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexamweightActionPerformed(evt);
            }
        });

        lblIdUser7.setText("Weight");

        lblIdUser12.setText("Weight");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitle)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblcourse)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblcourse1)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 111, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblIdUser)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtiduser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(lblIdUser1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblIdUser6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtassignmentweight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblIdUser5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtassignmentgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(42, 42, 42)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(lblIdUser3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtmodule, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblIdUser8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtexamgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblIdUser12)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtexamweight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(74, 74, 74)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(lblIdUser9)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtfinalgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(lblIdUser7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtfinalweight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblTitle))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcourse))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcourse1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdUser)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdUser1)
                    .addComponent(txtiduser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdUser3)
                    .addComponent(txtmodule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdUser6)
                    .addComponent(txtassignmentweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtexamweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfinalweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdUser7)
                    .addComponent(lblIdUser12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdUser5)
                    .addComponent(txtassignmentgrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdUser8)
                    .addComponent(txtexamgrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdUser9)
                    .addComponent(txtfinalgrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSubjectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSubjectsActionPerformed

    private void txtmoduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmoduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmoduleActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        consultar();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cboCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCourseActionPerformed

    private void txtassignmentgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtassignmentgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtassignmentgradeActionPerformed

    private void txtiduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiduserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtiduserActionPerformed

    private void txtexamgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexamgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtexamgradeActionPerformed

    private void txtfinalgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfinalgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfinalgradeActionPerformed

    private void txtfinalweightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfinalweightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfinalweightActionPerformed

    private void txtassignmentweightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtassignmentweightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtassignmentweightActionPerformed

    private void txtexamweightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexamweightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtexamweightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cboCourse;
    private javax.swing.JComboBox<String> cboSubjects;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblIdUser;
    private javax.swing.JLabel lblIdUser1;
    private javax.swing.JLabel lblIdUser12;
    private javax.swing.JLabel lblIdUser3;
    private javax.swing.JLabel lblIdUser5;
    private javax.swing.JLabel lblIdUser6;
    private javax.swing.JLabel lblIdUser7;
    private javax.swing.JLabel lblIdUser8;
    private javax.swing.JLabel lblIdUser9;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblcourse;
    private javax.swing.JLabel lblcourse1;
    private javax.swing.JTextField txtassignmentgrade;
    private javax.swing.JTextField txtassignmentweight;
    private javax.swing.JTextField txtexamgrade;
    private javax.swing.JTextField txtexamweight;
    private javax.swing.JTextField txtfinalgrade;
    private javax.swing.JTextField txtfinalweight;
    private javax.swing.JTextField txtiduser;
    private javax.swing.JTextField txtmodule;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
